### ISSUE TITLE
Error when run inside VS code

### ISSUE THREAD

**Issue by 7NT** [FilledStacks/stacked-example#11]
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
 lib/main.dart
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.4.11/lib/src/snackbar_service.dart:74:7: Error: Type 'SnackStatusCallback' not found.
      SnackStatusCallback onStatusChanged,
      ^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.4.11/lib/src/navigation_service.dart:94:35: Error: The getter 'defaultDurationTransition' isn't defined for the class '_GetImpl'.
 - '_GetImpl' is from 'package:get/get_core/src/get_main.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-3.15.0/lib/get_core/src/get_main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultDurationTransition'.
        duration: duration ?? Get.defaultDurationTransition,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.4.11/lib/src/navigation_service.dart:113:33: Error: The getter 'defaultDurationTransition' isn't defined for the class '_GetImpl'.
 - '_GetImpl' is from 'package:get/get_core/src/get_main.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-3.15.0/lib/get_core/src/get_main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultDurationTransition'.
      duration: duration ?? Get.defaultDurationTransition,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.4.11/lib/src/snackbar_service.dart:74:7: Error: 'SnackStatusCallback' isn't a type.
      SnackStatusCallback onStatusChanged,
      ^^^^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.4.11/lib/src/snackbar_service.dart:111:9: Error: No named parameter with the name 'onStatusChanged'.
        onStatusChanged: onStatusChanged,
        ^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-3.15.0/lib/get_navigation/src/snackbar/snack.dart:12:3: Context: Found this candidate, but the arguments don't match.
  GetBar({
  ^^^^^^

FAILURE: Build failed with an exception.
* Where:
Script '/Users/jun/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 900

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/jun/development/flutter/bin/flutter'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by 7NT** [comment]
fixed after upgrade all packages

**Comment by Vinamra2009** [comment]
Can you tell me how to fix this please

**Comment by 7NT** [comment]
I simply upgraded all dependencies packages in the YAML file

**Comment by dush999** [comment]
@Vinamra2009  run command "flutter pub upgrade"
