### ISSUE TITLE
Issues running with the latest Flutter 1.22

### ISSUE THREAD

**Issue by trauts2** [FilledStacks/stacked-example#8]
This app has been very handy to see a working stacked app with a recent and happily coexisting set of dependencies.  Looks like there are a variety of issues running against the latest Flutter release.  And also against current versions of key libraries like https://github.com/Milad-Akarie/auto_route_library/issues/250

It would be a huge help if someone from the core stacked team could do some freshening on this app so that it worked with the latest.  And where 3rd party libs are not the latest, if that is intentional and for good reasons, knowing why would be also helpful so that we don't continue to waste time trying to get everything to work together.

Btw, huge fan of Stacked here.  I'm still a relative newbie though or I'd do this myself.  Few hours wasted trying...

Stu

**Comment by FilledStacks** [comment]
Hey, there was a clash with the Router name from the new Navigator API introduced by flutter. The way to fix this is simply to change your import for auto_router from 

```dart
import 'app/router.gr.dart';
```

to 

```dart
import 'app/router.gr.dart' as auto_router;
```

and use it as 

```dart
onGenerateRoute: auto_router.Router().onGenerateRoute,
```
